#!/usr/bin/env bash
# behavior-check.sh — Compares CLI args generated by Python and Go SDKs
# for the same set of options. Detects behavioral divergences.
#
# Usage: ./scripts/behavior-check.sh [path-to-python-sdk]
# Exit code 0 = match, 1 = differences found

set -uo pipefail

PYTHON_SDK="${1:-../claude-code-sdk-python}"
GO_SDK="$(cd "$(dirname "$0")/.." && pwd)"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m'

ERRORS=0
TMPDIR_BASE=$(mktemp -d)
trap 'rm -rf "$TMPDIR_BASE"' EXIT

python_build_command() {
    local options_code="$1"
    python3 -c "
import sys
sys.path.insert(0, '$PYTHON_SDK/src')
from claude_agent_sdk.types import *
from claude_agent_sdk._internal.transport.subprocess_cli import SubprocessCLITransport

$options_code

transport = SubprocessCLITransport.__new__(SubprocessCLITransport)
transport._cli_path = '/usr/bin/claude'
transport._options = options
transport._is_streaming = True
cmd = transport._build_command()
for arg in cmd:
    print(arg)
" 2>/dev/null
}

go_build_command() {
    local options_code="$1"
    local test_name="$2"

    local tmpfile="$GO_SDK/internal/process/behavior_gen_test.go"
    cat > "$tmpfile" <<GOEOF
package process

import (
    "fmt"
    "testing"
)

func ${test_name}(t *testing.T) {
    cfg := Config{Streaming: true}
    $options_code
    args := BuildArgs(cfg)
    // Print full command (cli path + args)
    fmt.Println("/usr/bin/claude")
    for _, arg := range args {
        fmt.Println(arg)
    }
}
GOEOF

    (cd "$GO_SDK" && go test -v -run "^${test_name}$" ./internal/process/ 2>/dev/null \
        | grep -v "^=== " | grep -v "^--- " | grep -v "^ok " | grep -v "^PASS")

    rm -f "$tmpfile"
}

compare_args() {
    local label="$1"
    local py_options="$2"
    local go_options="$3"
    local test_name="TestBehavior$(echo "$label" | sed 's/[^a-zA-Z0-9]//g')"

    local py_out="$TMPDIR_BASE/py_args.txt"
    local go_out="$TMPDIR_BASE/go_args.txt"

    python_build_command "$py_options" > "$py_out" 2>/dev/null
    go_build_command "$go_options" "$test_name" > "$go_out" 2>/dev/null

    if [ ! -s "$py_out" ]; then
        echo -e "${YELLOW}SKIP${NC} $label — Python extraction failed"
        return
    fi
    if [ ! -s "$go_out" ]; then
        echo -e "${YELLOW}SKIP${NC} $label — Go extraction failed"
        return
    fi

    normalize_args() {
        local file="$1"
        local prev=""
        while IFS= read -r line; do
            if [[ "$line" == --* ]]; then
                if [ -n "$prev" ]; then echo "$prev"; fi
                prev="$line"
            else
                if [ -n "$prev" ]; then
                    echo "$prev=$line"
                    prev=""
                else
                    echo "$line"
                fi
            fi
        done < "$file"
        if [ -n "$prev" ]; then echo "$prev"; fi
    }

    normalize_args "$py_out" | sort > "$TMPDIR_BASE/py_norm.txt"
    normalize_args "$go_out" | sort > "$TMPDIR_BASE/go_norm.txt"

    local diff_out
    diff_out=$(diff "$TMPDIR_BASE/py_norm.txt" "$TMPDIR_BASE/go_norm.txt" 2>/dev/null || true)

    if [ -z "$diff_out" ]; then
        echo -e "${GREEN}OK${NC}   $label"
    else
        echo -e "${RED}FAIL${NC} $label"
        echo "$diff_out" | while IFS= read -r line; do
            case "$line" in
                "<"*) echo -e "  ${RED}Python only:${NC} ${line#< }" ;;
                ">"*) echo -e "  ${YELLOW}Go only:${NC}     ${line#> }" ;;
            esac
        done
        ERRORS=$((ERRORS + 1))
    fi
}

echo "Behavioral Parity Check (CLI args)"
echo "Python: $PYTHON_SDK"
echo "Go:     $GO_SDK"
echo ""

echo "=== Tool Control ==="
compare_args "allowed_tools" \
    "options = ClaudeAgentOptions(allowed_tools=['Read', 'Write', 'Bash'])" \
    'cfg.AllowedTools = []string{"Read", "Write", "Bash"}'

compare_args "disallowed_tools" \
    "options = ClaudeAgentOptions(disallowed_tools=['Bash'])" \
    'cfg.DisallowedTools = []string{"Bash"}'

echo ""
echo "=== Model & Prompt ==="
compare_args "model" \
    "options = ClaudeAgentOptions(model='claude-sonnet-4-5')" \
    'cfg.Model = "claude-sonnet-4-5"'

compare_args "fallback_model" \
    "options = ClaudeAgentOptions(fallback_model='claude-haiku-4-5')" \
    'cfg.FallbackModel = "claude-haiku-4-5"'

echo ""
echo "=== Budget ==="
compare_args "max_budget" \
    "options = ClaudeAgentOptions(max_budget_usd=10.5)" \
    'b := 10.5; cfg.MaxBudgetUSD = &b'

echo ""
echo "=== Session ==="
compare_args "session_id" \
    "options = ClaudeAgentOptions(session_id='550e8400')" \
    'cfg.SessionID = "550e8400"'

compare_args "continue" \
    "options = ClaudeAgentOptions(continue_conversation=True)" \
    'cfg.Continue = true'

compare_args "resume" \
    "options = ClaudeAgentOptions(resume='session-123')" \
    'cfg.Resume = "session-123"'

compare_args "max_turns" \
    "options = ClaudeAgentOptions(max_turns=5)" \
    'n := 5; cfg.MaxTurns = &n'

compare_args "fork" \
    "options = ClaudeAgentOptions(fork_session=True)" \
    'cfg.ForkSession = true'

compare_args "partial_msgs" \
    "options = ClaudeAgentOptions(include_partial_messages=True)" \
    'cfg.IncludePartialMessages = true'

compare_args "setting_sources" \
    "options = ClaudeAgentOptions(setting_sources=['user', 'project'])" \
    'cfg.SettingSources = []string{"user", "project"}'

echo ""
echo "=== Permission ==="
compare_args "perm_default" \
    "options = ClaudeAgentOptions(permission_mode='default')" \
    'cfg.PermissionMode = "default"'

compare_args "perm_bypass" \
    "options = ClaudeAgentOptions(permission_mode='bypassPermissions')" \
    'cfg.PermissionMode = "bypassPermissions"'

echo ""
echo "=== Effort ==="
compare_args "effort" \
    "options = ClaudeAgentOptions(effort='high')" \
    'cfg.Effort = "high"'

echo ""
echo "=== Betas ==="
compare_args "betas" \
    "options = ClaudeAgentOptions(betas=['context-1m-2025-08-07'])" \
    'cfg.Betas = []string{"context-1m-2025-08-07"}'

echo ""
echo "---"
if [ "$ERRORS" -gt 0 ]; then
    echo -e "${RED}$ERRORS behavioral difference(s) found${NC}"
    exit 1
else
    echo -e "${GREEN}Full behavioral parity${NC}"
    exit 0
fi
